---
- name: Install and manage Consul systemd service
  include_role:
    name: systemd_service
  vars:
    service_name: consul
    service_unit_template: consul.service.j2
    service_config_changed: "{{ consul_config }}"

