
# Temporary directory on Bastion hosts where Consul ACL tokens (s. 50-consul-acl playbook) 
# will be temporarily stored during the run, 
# with strict permissions, the folder will be removed at the end of the run
consul_tokens_tmp_dir: /root/.consul-acl
consul_tmp_management_token_path: "{{ consul_tokens_tmp_dir }}/.consul-mgmt-token"
consul_server_token_tmp_path_bastion: "{{ consul_tokens_tmp_dir }}/consul-server.token"
vault_consul_token_tmp_path_bastion: "{{ consul_tokens_tmp_dir }}/vault-backend.token"



consul_acl_policy: "consul-servers-acl-policy"
vault_acl_policy: "vault-acl-policy"
k8s_acl_policy: "k8s-acl-policy"

# Token files on Consul client hosts
consul_server_token_path: "/etc/consul.d/token.hcl"
consul_server_agent_token_raw_path: "/etc/consul.d/agent.token"
vault_consul_storage_config_path: "/etc/vault.d/consul.hcl"
vault_consul_token_path: "/etc/vault.d/consul.token"