vault_ssh_secrets_mount_path: "ssh"
vault_ssh_ca_config_path: "{{ vault_ssh_secrets_mount_path }}/config/ca"
vault_ssh_ca_public_key_file: "/var/lib/vault-state/trusted-user-ca-keys.pem"
vault_ssh_trusted_user_ca_keys_path: "/etc/ssh/trusted-user-ca-keys.pem"
vault_ssh_sshd_config_path: "/etc/ssh/sshd_config"
vault_ssh_admin_role_name: "admin-role"
vault_ssh_admin_allowed_users: "ansible"
vault_ssh_admin_default_user: "ansible"
vault_ssh_admin_ttl: "1h"
vault_ssh_admin_policy_name: "admin-ssh"
vault_ssh_admin_policy_file: "/var/lib/vault-state/admin-ssh-policy.hcl"
vault_ssh_admin_policy_hcl: |
	path "{{ vault_ssh_secrets_mount_path }}/sign/{{ vault_ssh_admin_role_name }}" {
		capabilities = ["update"]
	}
vault_ssh_admin_token_path_bastion: "/home/ansible/.vault/admin-ssh.token"
vault_ssh_admin_test_private_key_path: "/home/ansible/.ssh/id_ed25519_vault_admin"
vault_ssh_admin_test_public_key_path: "{{ vault_ssh_admin_test_private_key_path }}.pub"
vault_ssh_admin_test_signed_key_path: "/home/ansible/.ssh/id_ed25519_vault_admin-cert.pub"

