- hosts: bastion_primary
  become: false
  gather_facts: false
  vars_files:
    - ../../vars/bootstrap-tls-vault-consul.yaml
  tasks:
  - name: Enable Vault TLS mode for URL construction
    set_fact:
      vault_tls_enabled: true
      consul_tls_enabled: true
      
  # verify mTLS from Bastion to Vault
  - name: Verify Vault HTTPS API from Bastion
    include_role:
      name: verify_https
    vars:
      verify_https_name: "Vault api"
      verify_https_url: "{{ vault_api_health_addr }}"
      # mTLS client certs for Bastion → Vault
      verify_https_client_cert: "{{ bastion_client_auth_to_vault_cert_path }}"
      verify_https_client_key: "{{ bastion_client_auth_to_vault_key_path }}"
      # CA is now installed in system trust store, no need to specify
      verify_https_expected_status: [ 429, 501 ]
      
  # verify mTLS from Bastion to Consul
  - name: Verify Consul HTTPS API from Bastion
    include_role:
      name: verify_https
    vars:
      verify_https_name: "Consul api"
      verify_https_url: "{{ consul_api_leader_addr}}"
      # mTLS client certs for Bastion → Consul
      verify_https_client_cert: "{{ bastion_client_auth_to_consul_cert_path }}"
      verify_https_client_key: "{{ bastion_client_auth_to_consul_key_path }}"
      # CA is now installed in system trust store, no need to specify
