- name: Cleanup Consul ACL bootstrap material on Bastion
  hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - vars/consul-acl-vars.yaml
  tasks:
    - name: Remove Consul ACL bootstrap directory
      file:
        path: "{{ consul_tokens_tmp_dir }}"
        state: absent