- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../../vars/bootstrap-tls-vault-consul.yaml
  - ../../vars/consul-acl-vars.yaml
  vars:
    consul_acl_policies:
    - { name: "{{ consul_acl_policy }}", file: "30_policies/consul-servers.hcl.j2" }
    - { name: "{{ vault_acl_policy }}", file: "30_policies/vault.hcl.j2" }
    - { name: "{{ k8s_acl_policy }}", file: "30_policies/k8s.hcl.j2" }
  tasks:
  - set_fact:
      vault_tls_enabled: true
      consul_tls_enabled: true
  - name: Load Consul management token
    import_tasks: tasks/read_mgmt_token.yaml

  - name: Ensure Consul ACL policies are present
    include_tasks: tasks/upsert_acl_policy.yaml
    loop: "{{ consul_acl_policies }}"
    loop_control:
      loop_var: policy_item
      label: "{{ policy_item.name }}"
