- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../../vars/bootstrap-tls-vault-consul.yaml
  - vars/consul-acl-vars.yaml
  tasks:
  - name: Load Consul management token
    import_tasks: tasks/read_mgmt_token.yaml

  - name: Create Consul server agent token
    command: >
      consul acl token create
      -description "Consul server agent token"
      -policy-name "{{ consul-acl-policy }}"
      -format json
      -http-addr={{ consul_api_addr }}
      -client-cert={{ bastion_client_auth_to_consul_cert_path }}
      -client-key={{ bastion_client_auth_to_consul_key_path }}
      -token={{ consul_mgmt_token }}
    register: consul_server_token
    changed_when: true
    no_log: true

  - name: Persist Consul server agent token in tmp file
    copy:
      content: "{{ consul_server_token.stdout | from_json | json_query('SecretID') }}"
      dest: "{{ consul_server_token_tmp_path_bastion }}"
      owner: root
      group: root
      mode: "0600"
    no_log: true
