- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../../vars/bootstrap-tls-vault-consul.yaml
  - vars/consul-acl-vars.yaml
  tasks:
  - name: Load Consul management token
    import_tasks: tasks/read_mgmt_token.yaml

  - name: Create Consul server agent token
    uri:
      url: "{{ consul_api_addr }}/v1/acl/token"
      method: PUT
      body_format: json
      body:
        Description: "Consul server agent token"
        Policies:
        - Name: "{{ consul-acl-policy }}"
      headers:
        X-Consul-Token: "{{ consul_mgmt_token }}"
      status_code: 200
      validate_certs: true
      client_cert: "{{ bastion_client_auth_to_consul_cert_path }}"
      client_key: "{{ bastion_client_auth_to_consul_key_path }}"
    register: consul_server_token_response
    changed_when: true
    no_log: true

  - name: Persist Consul server agent token in tmp file
    copy:
      content: "{{ consul_server_token_response.json.SecretID }}"
      dest: "{{ consul_server_token_tmp_path_bastion }}"
      owner: root
      group: root
      mode: "0600"
    no_log: true
