- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../../vars/bootstrap-tls-vault-consul.yaml
  - vars/consul-acl-vars.yaml

  tasks:
  - name: Load Consul management token
    import_tasks: tasks/read_mgmt_token.yaml

  - name: Create Vault Consul token
    command: >
      consul acl token create
      -description "Vault Consul backend token"
      -policy-name "{{ vault-acl-policy }}"
      -format json
      -http-addr={{ consul_api_addr }}
      -ca-file={{ bastion_ca_cert_path }}
      -client-cert={{ bastion_client_auth_to_consul_cert_path }}
      -client-key={{ bastion_client_auth_to_consul_key_path }}
      -token={{ consul_mgmt_token }}
    register: vault_consul_token
    changed_when: true
    no_log: true

  - name: Persist Vault Consul backend token in tmp file
    copy:
      content: "{{ vault_consul_token.stdout | from_json | json_query('SecretID') }}"
      dest: "{{ vault_consul_token_tmp_path_bastion }}"
      owner: root
      group: root
      mode: "0600"
    no_log: true
