- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../../vars/bootstrap-tls-vault-consul.yaml
  - ../../vars/consul-acl-vars.yaml

  tasks:
  - set_fact:
      vault_tls_enabled: true
      consul_tls_enabled: true
  - name: Load Consul management token
    import_tasks: tasks/read_mgmt_token.yaml

  - name: Create Vault Consul token
    uri:
      url: "{{ consul_api_addr }}/v1/acl/token"
      method: PUT
      body_format: json
      body:
        Description: "Vault Consul backend token"
        Policies:
        - Name: "{{ vault_acl_policy }}"
      headers:
        X-Consul-Token: "{{ consul_mgmt_token }}"
      status_code: 200
      validate_certs: true
      client_cert: "{{ bastion_client_auth_to_consul_cert_path }}"
      client_key: "{{ bastion_client_auth_to_consul_key_path }}"
    register: vault_consul_token_response
    changed_when: true
    no_log: true

  - name: Persist Vault Consul backend token in tmp file
    copy:
      content: "{{ vault_consul_token_response.json.SecretID }}"
      dest: "{{ vault_consul_token_tmp_path_bastion }}"
      owner: root
      group: root
      mode: "0600"
    no_log: true
