- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../vars/bootstrap-tls-vault-consul.yaml
  - vars/consul-acl-vars.yaml

  tasks:
  - name: Load Consul management token
    import_tasks: tasks/read_mgmt_token.yaml

  - name: Create Vault Consul token
    consul_acl_token:
      description: "Vault Consul backend token"
      policies:
      - name: vault
      token: "{{ consul_mgmt_token }}"
      url: "{{ consul_api_addr }}"
      ca_path: "{{ bastion_ca_cert_path }}"
      client_cert: "{{ bastion_client_auth_to_consul_cert_path }}"
      client_key: "{{ bastion_client_auth_to_consul_key_path }}"
    register: vault_consul_token
    no_log: true

  - name: Persist Vault Consul backend token in tmp file
    copy:
      content: "{{ vault_consul_token.secret }}"
      dest: "{{ vault_consul_token_tmp_path_bastion }}"
      owner: root
      group: root
      mode: "0600"
    no_log: true
