- hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
    - ../../vars/bootstrap-tls-vault-consul.yaml
    - ../../vars/consul-acl-vars.yaml
  tasks:
    - name: Create bastion agent-read token
      community.hashi_vault.consul_acl_token:
        name: bastion-agent-read-token
        policies:
          - "{{ bastion_agent_read_acl_policy }}"
        state: present
        management_token: "{{ lookup('file', consul_tmp_management_token_path) }}"
      register: bastion_agent_read_token

    - name: Write bastion agent-read token to file
      copy:
        content: "{{ bastion_agent_read_token.secret_id }}"
        dest: "{{ bastion_agent_read_token_path }}"
        owner: ansible
        group: ansible
        mode: '0600'
