  - name: Read bastion agent-read token from file
    slurp:
      src: "{{ bastion_consul_read_token_path }}"
    register: bastion_agent_read_token_file
    no_log: true

  - name: Set bastion agent-read token fact
    set_fact:
      bastion_agent_read_token: "{{ bastion_agent_read_token_file.content | b64decode | trim }}"
    changed_when: false
    no_log: true
- name: Verify Consul ACLs from Bastion
  hosts: bastion_primary
  become: true
  gather_facts: false
  vars_files:
  - ../../vars/bootstrap-tls-vault-consul.yaml
  - ../../vars/consul-acl-vars.yaml
  tasks:

  - name: Authenticated agent-read: can read Consul agent self
    uri:
      url: "{{ consul_api_internal_health_addr }}"
      method: GET
      status_code: 200
      validate_certs: true
      ca_path: "{{ bastion_ca_cert_path }}"
      client_cert: "{{ bastion_client_auth_to_consul_cert_path }}"
      client_key: "{{ bastion_client_auth_to_consul_key_path }}"
      headers:
        X-Consul-Token: "{{ bastion_agent_read_token }}"
    register: bastion_agent_self
    changed_when: false

  - name: HTTP API is not reachable from Bastion
    uri:
      url: "http://{{ consul_service_name }}:{{ consul_http_port }}{{ consul_api_leader_path }}"
      method: GET
      status_code: 0
    register: http_test
    failed_when: http_test is succeeded
    changed_when: false
