---
- name: Install and manage Vault systemd service
  include_role:
    name: systemd_service
  vars:
    service_name: vault
    service_unit_template: vault.service.j2
    service_config_changed: "{{ vault_config }}"


