# the fact affects the configuration template and is used to conditionally render TLS settings
# must be set before re-rendering the configuration
# set_fact stores the variable as a host-level fact
# so it works here in the second play because it runs on the same hosts
# otherwise, the fact set in one play would not be automatically shared with the second play
- name: Set Consul TLS mode to disabled
  hosts: consul
  gather_facts: false
  tasks:
    - name: Disable Consul TLS mode
      set_fact:
        consul_tls_enabled: false

- name: Install Consul with TLS disabled
  hosts: consul
  become: true
  roles:
    - consul
