---
# TLS material is first generated on the primary Bastion host (where Ansible controller is executed), 
# including client certificates for other Bastion hosts to auth to Vault and Consul. 
# This playbook distributes the TLS material from the primary Bastion to all other Bastion hosts.



- name: Install Bastion client TLS material for Consul and Vault on each Bastion host
  hosts: bastion
  gather_facts: true
  become: true
  vars_files:
    - ../vars/bootstrap-tls-vault-consul.yaml
  tasks:
    - name: Ensure TLS directories for auth to Consul as client exist on this Bastion 
      file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - path: "{{ bastion_ca_cert_path | dirname }}"
          mode: "0755"
        - path: "{{ bastion_client_auth_to_consul_cert_path | dirname }}"
          mode: "0755"
        - path: "{{ bastion_client_auth_to_vault_cert_path | dirname }}"
          mode: "0755"

    - name: Copy CA certificate from primary Bastion to this Bastion
      copy:
        src: "{{ bastion_ca_cert_path }}"
        dest: "{{ bastion_ca_cert_path }}"
        owner: root
        group: root
        mode: "0644"

    # Bastion to Consul auth certs
    ###############################################################################
    ######## USAGE ################################################################
    # export CONSUL_CACERT={{ bastion_ca_cert_path }}
    # export CONSUL_CLIENT_CERT={{ bastion_client_auth_to_consul_cert_path }}
    # export CONSUL_CLIENT_KEY={{ bastion_client_auth_to_consul_key_path }}
    ###############################################################################

    - name: Copy Bastion's Consul-client certificate from primary Bastion to this Bastion
      copy:
        src: "{{ bastion_tmp_tls_dir_for_consul_clients }}/{{ inventory_hostname }}/{{ consul_client_cert_file }}"
        dest: "{{ bastion_client_auth_to_consul_cert_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Copy Bastion's Consul-client private key from primary Bastion to this Bastion
      copy:
        src: "{{ bastion_tmp_tls_dir_for_consul_clients }}/{{ inventory_hostname }}/{{ consul_client_key_file }}"
        dest: "{{ bastion_client_auth_to_consul_key_path }}"
        owner: root
        group: root
        mode: "0600"

    ###############################################################################
    #  Bastion → Vault
    ###############################################################################

    ################ USAGE ########################################################
    # export VAULT_ADDR=https://{{ vault_private_ip }}:{{ vault_api_port }}
    # export VAULT_CACERT={{ bastion_ca_cert_path }}
    # export VAULT_CLIENT_CERT={{ bastion_client_auth_to_vault_cert_path }}
    # export VAULT_CLIENT_KEY={{ bastion_client_auth_to_vault_key_path }}
    ###############################################################################

    - name: Copy Bastion's Vault-client certificate from primary Bastion to this Bastion
      copy:
        src: "{{ bastion_tmp_tls_dir_for_vault_clients }}/{{ inventory_hostname }}/{{ vault_client_cert_file }}"
        dest: "{{ bastion_client_auth_to_vault_cert_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Copy Bastion's Vault-client private key from primary Bastion to this Bastion
      copy:
        src: "{{ bastion_tmp_tls_dir_for_vault_clients }}/{{ inventory_hostname }}/{{ vault_client_key_file }}"
        dest: "{{ bastion_client_auth_to_vault_key_path }}"
        owner: root
        group: root
        mode: "0600"

    ###############################################################################
    # Sanity checks
    ###############################################################################
    - name: Assert required TLS files exist on Bastion
      include_role:
        name: assert_paths
      vars:
        required_paths:
        - path: "{{ bastion_tls_dir }}"
          type: folder
          owner: root
          group: root
          mode: "0755"
        - path: "{{ bastion_ca_cert_path }}"
          type: file
          owner: root
          group: root
          mode: "0644"
        - path: "{{ bastion_client_auth_to_consul_certs_dir }}"
          type: folder
          owner: root
          group: root
          mode: "0755"
        - path: "{{ bastion_client_auth_to_consul_cert_path }}"
          type: file
          owner: root
          group: root
          mode: "0644"
        - path: "{{ bastion_client_auth_to_consul_key_path }}"
          type: file
          owner: root
          group: root
          mode: "0600"
        - path: "{{ bastion_client_auth_to_vault_certs_dir }}"
          type: folder
          owner: root
          group: root
          mode: "0755"
        - path: "{{ bastion_client_auth_to_vault_cert_path }}"
          type: file
          owner: root
          group: root
          mode: "0644"
        - path: "{{ bastion_client_auth_to_vault_key_path }}"
          type: file
          owner: root
          group: root
          mode: "0600"
