---
### Bootstrap TLS (phase 2): distribute TLS material and enable TLS on services

##### On Vault
# - Install TLS material generated on Bastion
#   - CA certificate to validate client certs
#   - Vault server certificate + private key
#   - Vault client certificate + private key (for Vault → Consul mTLS)
# - Rewrite Vault config: listener → HTTPS, api_addr → HTTPS
# - Restart Vault

#### On Consul
# Install TLS material generated on Bastion
#   - CA certificate to validate client certs
#   - Consul server certificate + private key
# Rewrite Consul config: HTTP → HTTPS (API), Restart Consul

# Should fail if Vault already has TLS enabled
# The playbook must never be rerun after TLS bootstrap is completed






- name: Install Bastion client TLS material for Consul and Vault on each Bastion host
  hosts: bastion
  gather_facts: true
  become: true
  vars_files:
    - ../vars/bootstrap-tls-vault-consul.yaml
  tasks:
    - name: Install Bastion client certificate for Consul mTLS
      import_tasks: ../tasks/bootstrap-tls-vault-consul/33_distribute_tls_to_other_bastions.yaml
