# For THIS host/group, SSH as ansible user by default;
ansible_user: ansible
# become: false is default Ansible behaviour


# DNS
dns_entries:
  # later for HA should be changed to load balancer in front of Vault nodes
  vault:
    host: "{{ groups['vault'][0] }}"
    names:
    - "{{ vault_service_name }}"
    - "{{ groups['vault'][0] }}"

  consul:
    # for Consul it doesn't matter which node we point to since they replicate data among themselves
    host: "{{ groups['consul_servers'][0] }}"
    names:
    - "{{ consul_service_name }}"
    - "{{ groups['consul_servers'][0] }}"
  
  oidc:
    # we are not going to have more than one OIDC server
    host: "{{ groups['oidc'][0] }}"
    names:
    - "{{ oidc_service_name }}"
    - "{{ groups['oidc'][0] }}"
    


######################################################
######### Consul  ####################################
######################################################
# TLS lifecycle flag (flipped via set_fact at initial installation when TLS is still disabled)
consul_tls_enabled: true

# HTTP or HTTPS depending on TLS phase
consul_agent_api_scheme: "{{ 'https' if consul_tls_enabled else 'http' }}"

# internally used addresses
# will work with gather_facts: false as well, 
# since the value is derived from inventory variables 
# with a fallback to inventory_hostname
internal_address: "{{ ansible_host | default(inventory_hostname) }}"

# local interface the Consul agent binds to
# affects listeners and gossip
# never used by other services directly
consul_internal_bind_addr: "{{ internal_address }}"

# Consul internal – cluster identity
# used only for Consul ↔ Consul communication
consul_internal_advertise_addr: "{{ internal_address }}"

consul_service_name: "consul.service.internal"

# Port of the Consul agent API (8501 = HTTPS, 8500 = HTTP)
consul_http_port: 8500
consul_https_port: 8501
consul_dns_port: 8600
consul_agent_api_port: "{{ consul_https_port if consul_tls_enabled else consul_http_port }}"


# Address advertised by the Consul agent for client access; HTTP/HTTPS API
# used by Vault, Bastion, kubectl plugins, etc.
consul_api_leader_path: /v1/status/leader
consul_api_self_path: /v1/agent/self
consul_key_value_path: /v1/kv

consul_api_addr: "{{ consul_agent_api_scheme }}://{{ consul_service_name }}:{{ consul_agent_api_port }}"
consul_api_leader_addr: "{{ consul_api_addr }}{{ consul_api_leader_path }}"
consul_api_health_addr: "{{ consul_api_addr }}{{ consul_api_self_path }}"
consul_api_key_value_addr: "{{ consul_api_addr }}{{ consul_key_value_path }}"

# for local health checks
consul_api_internal_leader_addr: "{{ consul_agent_api_scheme }}://{{ ansible_default_ipv4.address }}:{{ consul_agent_api_port }}{{ consul_api_leader_path }}"
consul_api_internal_health_addr: "{{ consul_agent_api_scheme }}://{{ ansible_default_ipv4.address }}:{{ consul_agent_api_port }}{{ consul_api_self_path }}"


######################################################
######### Vault  #####################################
######################################################

# TLS lifecycle flag (flipped via set_fact at initial installation when TLS is still disabled)
vault_tls_enabled: true

# HTTP or HTTPS depending on TLS phase
vault_api_scheme: "{{ 'https' if vault_tls_enabled else 'http' }}"

vault_service_name: "vault.service.internal"

vault_api_port: 8200
vault_cluster_port: 8201



# internally used addresses
# will work with gather_facts: false as well, 
# since the value is derived from inventory variables 
# with a fallback to inventory_hostname
vault_internal_address: "{{ ansible_host | default(inventory_hostname) }}"
vault_api_addr: "{{ vault_api_scheme }}://{{ vault_service_name }}:{{ vault_api_port }}"
vault_api_health_path: "/v1/sys/health"
vault_api_health_internal_addr: "{{ vault_api_scheme }}://{{ ansible_default_ipv4.address }}:{{ vault_api_port }}{{ vault_api_health_path }}"
vault_api_health_addr: "{{ vault_api_addr }}{{ vault_api_health_path }}"
vault_cluster_addr: "{{ vault_api_scheme }}://{{ vault_internal_address }}:{{ vault_cluster_port}}"

######################################################
######### Consul-Vault  ##############################
######################################################

#key prefix inside Consul’s KV store where Vault data will be stored
vault_prefix_in_consul_store: "vault/"


### OIDC server

oidc_service_name: "keycloak.service.internal"