#The Consul datacenter name this agent belongs to
# Raft consensus happens per datacenter
# ACLs, intentions, and services are namespaced by datacenter
# WAN federation happens between datacenters
consul_datacenter: dc1



# Installation and configuration
consul_version: "1.22.2"

# User / group
consul_user: consul
consul_group: consul

# Paths
consul_data_dir: /opt/consul/data
consul_config_dir: /etc/consul.d
consul_install_dir: /usr/local/bin
consul_binary_path: "{{consul_install_dir}}/consul"



# Logging
consul_log_level: INFO

# ACLs (for consul-acl playbook)
consul_server_agent_token_path: "/etc/consul.d/token.hcl"
