vault_version: "1.21.2"

vault_user: vault
vault_group: vault

# Installation and configuration paths
vault_data_dir: /opt/vault/data
vault_config_dir: /etc/vault.d
vault_install_dir: /usr/local/bin
vault_binary_path: "{{ vault_install_dir }}/vault"




# ACLs (for consul-acl playbook)
vault_consul_agent_token_path: "/etc/vault.d/consul.hcl"